# Generated by Django 4.0.5 on 2022-07-15 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_comm'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comm',
            new_name='Comment',
        ),
    ]
